[package]
name = "ebcdict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ebcdict_converter = {path="../ebcdict_converter"}